---
- hosts: 127.0.0.1
  connection: local
 
  tasks:

  - name: install latest version of Apache 
    yum:
      name: httpd
      state: present

  - name: install php dependencies
    action: yum pkg={{ item }} state=installed
    with_items:
      - php
      - php-mysql

  - name: Installing Mysql server..
    action: yum pkg={{ item }} state=installed
    with_items:
      - mysql-server
      - mysql

  - name: Starting database service..
    action: service name=mysqld state=started

  - name: Setup Root credentials on Mysql
    mysql_user: 
      - name: root
      - host: {{ item }}
      - password: avengers
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
