---
- hosts: 127.0.0.1
  connection: local
  vars:
     database: avengers
     dbuser: avengers
     dbpass: avengers
 
  tasks:

  - name: install latest version of Apache 
    yum:
      name: httpd
      state: present

  - name: install php dependencies
    action: yum pkg={{ item }} state=installed
    with_items:
      - php
      - php-mysql

  - name: Installing Mysql server..
    action: yum pkg={{ item }} state=installed
    with_items:
      - mysql-server
      - mysql
      - MySQL-python

  - name: Starting database service..
    action: service name=mysqld state=started enabled=yes

  - name: Create mysql user..
    mysql_user: name={{ dbuser }} password={{ dbpass }} priv='*.*:ALL' state=present

  - name: Create database name..
    mysql_db: name={{ database }} state=present

  - name: download the wordpress package..
    unarchive: src=https://wordpress.org/latest.zip dest=/var/www/ remote_src=yes
 
  - name: renaming and the application
    command: sudo mv /var/www/wordpress /var/www/html

  - name: copy sample configuration file
    copy:
      src: /var/www/html/wordpress/wp-config-sample.php
      dest: /var/www/html/wordpress/wp-config.php
     
  - name: configure application's database details..
    sudo: yes
    lineinfile:
       dest=/var/www/html/wordpress/wp-config.php
       regexp="{{ item.regexp }}"
       line="{{ item.line }}"
    with_items:
      - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{ dbuser }}')"}
      - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{ database }}');"}
      - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_NAME', '{{ dbpass }}');"}


